# Generated by Django 5.0 on 2026-03-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('preferred_language', models.CharField(choices=[('sk', 'Slovak'), ('cz', 'Czech')], default='sk', max_length=2)),
                ('source', models.CharField(default='lead_magnet', max_length=80)),
                ('stage', models.CharField(choices=[('new', 'New'), ('nurturing', 'Nurturing'), ('qualified', 'Qualified'), ('booked', 'Booked'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('consent_privacy', models.BooleanField(default=False)),
                ('consent_marketing', models.BooleanField(default=False)),
                ('consent_at', models.DateTimeField(auto_now_add=True)),
                ('consent_version', models.CharField(default='v1', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('brevo_contact_id', models.CharField(blank=True, max_length=80)),
                ('brevo_synced_at', models.DateTimeField(blank=True, null=True)),
                ('brevo_sync_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
