"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import json
import os
import sys
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_env_file(file_path):
    if not file_path.exists():
        return
    for raw_line in file_path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        # Do not override variables already provided by the process environment.
        os.environ.setdefault(key, value)


# Load local environment variables from backend/.env when present.
load_env_file(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

def env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def env_list(name, default=''):
    value = os.environ.get(name, default)
    return [item.strip() for item in value.split(',') if item.strip()]


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', False)
IS_RUNSERVER = len(sys.argv) > 1 and sys.argv[1] == 'runserver'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '').strip()
if not SECRET_KEY:
    if DEBUG or IS_RUNSERVER:
        # Local-only fallback for developer convenience.
        SECRET_KEY = 'django-insecure-local-dev-only'
    else:
        raise ImproperlyConfigured('DJANGO_SECRET_KEY must be set when DEBUG=False.')

if not DEBUG:
    if SECRET_KEY.startswith('django-insecure-') or len(set(SECRET_KEY)) < 5 or len(SECRET_KEY) < 50:
        raise ImproperlyConfigured('DJANGO_SECRET_KEY is too weak for production use.')

ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1')
if not DEBUG and not ALLOWED_HOSTS:
    raise ImproperlyConfigured('DJANGO_ALLOWED_HOSTS must be configured when DEBUG=False.')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'api',
]

AUTHENTICATION_BACKENDS = [
    'api.auth_backends.UsernameOrEmailBackend',
    'django.contrib.auth.backends.ModelBackend',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = env_list('DJANGO_CORS_ALLOWED_ORIGINS', '')

# Local Vite dev server needs CORS when backend runs on 8000.
if not CORS_ALLOWED_ORIGINS and IS_RUNSERVER:
    CORS_ALLOWED_ORIGINS = [
        'http://localhost:4028',
        'http://127.0.0.1:4028',
        'http://localhost:4173',
        'http://127.0.0.1:4173',
        'http://localhost:5173',
        'http://127.0.0.1:5173',
    ]

CSRF_TRUSTED_ORIGINS = env_list('DJANGO_CSRF_TRUSTED_ORIGINS', '')

if not CSRF_TRUSTED_ORIGINS and IS_RUNSERVER:
    CSRF_TRUSTED_ORIGINS = [
        'http://localhost:4028',
        'http://127.0.0.1:4028',
        'http://localhost:4173',
        'http://127.0.0.1:4173',
        'http://localhost:5173',
        'http://127.0.0.1:5173',
    ]

SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
REFERRER_POLICY = 'strict-origin-when-cross-origin'
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # Keep HTTPS enforcement in production, but avoid local dev redirect loops.
    SECURE_SSL_REDIRECT = False if IS_RUNSERVER else env_bool('DJANGO_SECURE_SSL_REDIRECT', True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool('DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS', True)
    SECURE_HSTS_PRELOAD = env_bool('DJANGO_SECURE_HSTS_PRELOAD', True)

# Email backend configuration for lead notifications and result emails.
EMAIL_BACKEND = os.environ.get('DJANGO_EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.environ.get('DJANGO_EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('DJANGO_EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('DJANGO_EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('DJANGO_EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = env_bool('DJANGO_EMAIL_USE_TLS', True)
EMAIL_USE_SSL = env_bool('DJANGO_EMAIL_USE_SSL', False)
EMAIL_TIMEOUT = int(os.environ.get('DJANGO_EMAIL_TIMEOUT', '10'))
DEFAULT_FROM_EMAIL = os.environ.get('DJANGO_DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'no-reply@habluj.local')
SERVER_EMAIL = os.environ.get('DJANGO_SERVER_EMAIL', DEFAULT_FROM_EMAIL)

# Keep lead capture independent from third-party services by default.
LEAD_EXTERNAL_INTEGRATIONS_ENABLED = env_bool('LEAD_EXTERNAL_INTEGRATIONS_ENABLED', False)

# Payments (GoPay)
GOPAY_CLIENT_ID = os.environ.get('GOPAY_CLIENT_ID', '').strip()
GOPAY_CLIENT_SECRET = os.environ.get('GOPAY_CLIENT_SECRET', '').strip()
GOPAY_GOID = os.environ.get('GOPAY_GOID', '').strip()
GOPAY_WEBHOOK_SECRET = os.environ.get('GOPAY_WEBHOOK_SECRET', '').strip()
GOPAY_CHECKOUT_BASE_URL = os.environ.get('GOPAY_CHECKOUT_BASE_URL', 'https://gate.gopay.cz').strip()
BOOKING_EUR_TO_CZK_RATE = os.environ.get('BOOKING_EUR_TO_CZK_RATE', '25')
BOOKING_PAYMENT_TTL_MINUTES = int(os.environ.get('BOOKING_PAYMENT_TTL_MINUTES', '15'))
BOOKING_CLASS_MINUTES = int(os.environ.get('BOOKING_CLASS_MINUTES', '60'))
BOOKING_LEAD_TIME_HOURS = int(os.environ.get('BOOKING_LEAD_TIME_HOURS', '12'))
BOOKING_CHANGE_WINDOW_HOURS = int(os.environ.get('BOOKING_CHANGE_WINDOW_HOURS', '24'))
BOOKING_DEFAULT_BUFFER_MINUTES = int(os.environ.get('BOOKING_DEFAULT_BUFFER_MINUTES', '10'))
BOOKING_TEACHER_TIMEZONE = os.environ.get('BOOKING_TEACHER_TIMEZONE', 'Europe/Madrid')
GOOGLE_CALENDAR_ID = os.environ.get('GOOGLE_CALENDAR_ID', '').strip()
GOOGLE_SERVICE_ACCOUNT_INFO = {}
_google_sa_raw = os.environ.get('GOOGLE_SERVICE_ACCOUNT_JSON', '').strip()
if _google_sa_raw:
    try:
        GOOGLE_SERVICE_ACCOUNT_INFO = json.loads(_google_sa_raw)
    except json.JSONDecodeError:
        GOOGLE_SERVICE_ACCOUNT_INFO = {}

if not DEBUG and (GOPAY_CLIENT_ID or GOPAY_CLIENT_SECRET or GOPAY_GOID) and not GOPAY_WEBHOOK_SECRET:
    raise ImproperlyConfigured('GOPAY_WEBHOOK_SECRET must be set when GoPay is configured and DEBUG=False.')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': os.environ.get('DRF_THROTTLE_ANON', '60/min'),
        'user': os.environ.get('DRF_THROTTLE_USER', '240/min'),
        'student_login': os.environ.get('DRF_THROTTLE_STUDENT_LOGIN', '10/min'),
        'student_register': os.environ.get('DRF_THROTTLE_STUDENT_REGISTER', '5/min'),
        'lead_create': os.environ.get('DRF_THROTTLE_LEAD_CREATE', '15/min'),
        'gopay_webhook': os.environ.get('DRF_THROTTLE_GOPAY_WEBHOOK', '120/min'),
    },
}

# Avoid test flakiness from login throttling across the test suite.
if 'test' in sys.argv:
    REST_FRAMEWORK['DEFAULT_THROTTLE_CLASSES'] = []

# Request and upload hard limits to reduce abuse/cost impact.
DATA_UPLOAD_MAX_MEMORY_SIZE = int(os.environ.get('DJANGO_DATA_UPLOAD_MAX_MEMORY_SIZE', str(2 * 1024 * 1024)))
FILE_UPLOAD_MAX_MEMORY_SIZE = int(os.environ.get('DJANGO_FILE_UPLOAD_MAX_MEMORY_SIZE', str(5 * 1024 * 1024)))
DATA_UPLOAD_MAX_NUMBER_FIELDS = int(os.environ.get('DJANGO_DATA_UPLOAD_MAX_NUMBER_FIELDS', '2000'))

# Student material upload policy.
STUDENT_MATERIAL_MAX_UPLOAD_BYTES = int(os.environ.get('STUDENT_MATERIAL_MAX_UPLOAD_BYTES', str(10 * 1024 * 1024)))
STUDENT_MATERIAL_ALLOWED_EXTENSIONS = [ext.lower().lstrip('.') for ext in env_list(
    'STUDENT_MATERIAL_ALLOWED_EXTENSIONS',
    'pdf,txt,doc,docx,png,jpg,jpeg,webp,mp3,wav,m4a,mp4,mov'
)]

# Progressive auth lock by IP (login/register).
AUTH_IP_ATTEMPT_WINDOW_SECONDS = int(os.environ.get('AUTH_IP_ATTEMPT_WINDOW_SECONDS', '3600'))
AUTH_IP_LOCK_MIN_FAILURES = int(os.environ.get('AUTH_IP_LOCK_MIN_FAILURES', '5'))
AUTH_IP_LOCK_BASE_SECONDS = int(os.environ.get('AUTH_IP_LOCK_BASE_SECONDS', '60'))
AUTH_IP_LOCK_MAX_SECONDS = int(os.environ.get('AUTH_IP_LOCK_MAX_SECONDS', '3600'))
